# Generated by Django 6.0.4 on 2026-04-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_remove_vote_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptition_request_model',
            name='party_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
